all:
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/as-skitter.ungraph-75000.txt --dest_dir `pwd`/output1  --unweighted --undirected > log1.txt
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/ca-AstroPh.txt --dest_dir `pwd`/output2  --unweighted --undirected > log2.txt
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/cit-HepPh.txt --dest_dir `pwd`/output3  --unweighted --undirected > log3.txt
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/cit-HepTh.txt --dest_dir `pwd`/output4  --unweighted --undirected > log4.txt
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/com-amazon.ungraph-75000.txt --dest_dir `pwd`/output5  --unweighted --undirected > log5.txt
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/com-dblp.ungraph-75000.txt --dest_dir `pwd`/output6  --unweighted --undirected > log6.txt
	python /home/ubuntu/phase2/graphminer/gm_main.py --file /home/ubuntu/phase2/data/email-Enron.ungraph.txt --dest_dir `pwd`/output7  --unweighted --undirected > log7.txt

